M48
; DRILL file {KiCad (6.0.9-0)} date 2024 March 23, Saturday 13:07:17
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-23T13:07:17+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X3.6417Y-4.311
X3.6417Y-4.4094
X3.8386Y-4.1142
X4.0354Y-4.311
X4.0354Y-4.4094
T0
M30
