M48
; DRILL file {KiCad (6.0.9-0)} date 2024 May 22, Wednesday 19:49:44
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-22T19:49:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X3.6417Y-4.311
X3.6417Y-4.4094
X3.8386Y-4.1142
X4.0354Y-4.311
X4.0354Y-4.4094
T0
M30
